Update azure-pipelines.yml for Azure Pipelines

diff --git a/src/ClientApp/azure-pipelines.yml b/src/ClientApp/azure-pipelines.yml
--- a/src/ClientApp/azure-pipelines.yml
+++ b/src/ClientApp/azure-pipelines.yml
@@ -91,13 +91,13 @@ stages:
               echo $(releaseSemVer)
               az login --service-principal -u $(azureArmClientId) -p $(azureArmClientSecret) --tenant $(azureArmTenantId)
               # upload content to container versioned folder
-              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\demo" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.html" --content-type "text/html"
-              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\demo" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.js" --content-type "application/javascript"
-              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\demo" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.js.map" --content-type "application/octet-stream"
-              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\demo" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.json" --content-type "application/json"
-              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\demo" --account-name $(azureStorageAccountName) --pattern "*.txt" --content-type "text/plain"
+              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\$(releaseSemVer)" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.html" --content-type "text/html"
+              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\$(releaseSemVer)" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.js" --content-type "application/javascript"
+              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\$(releaseSemVer)" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.js.map" --content-type "application/octet-stream"
+              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\$(releaseSemVer)" --account-name $(azureStorageAccountName) --content-encoding br --pattern "*.json" --content-type "application/json"
+              az storage blob upload-batch -s "$(Pipeline.Workspace)/drop" --destination "\$web\$(releaseSemVer)" --account-name $(azureStorageAccountName) --pattern "*.txt" --content-type "text/plain"
               # target new version
-              az cdn endpoint update --resource-group $(azureResourceGroup) --profile-name $(azureCdnName) --name $(azureCdnName) --origin-path '/demo'
+              az cdn endpoint update --resource-group $(azureResourceGroup) --profile-name $(azureCdnName) --name $(azureCdnName) --origin-path '/$(releaseSemVer)'
               AZURE_CDN_ENDPOINT_HOSTNAME=$(az cdn endpoint show --resource-group $(azureResourceGroup) --name $(azureCdnName) --profile-name $(azureCdnName) --query hostName -o tsv)
               echo "Azure CDN endpooint host ${AZURE_CDN_ENDPOINT_HOSTNAME}"
               echo '##vso[task.setvariable variable=azureCndEndpointHost]'$AZURE_CDN_ENDPOINT_HOSTNAME
@@ -105,6 +105,6 @@ stages:
           
           - script: |
               liveVersion=$(curl --fail --silent "https://$(azureCndEndpointHost)/semver.txt")
-              [[ $liveVersion == demo ]] && echo -e "\033[1;32m## [Passed] website validation Ok: $liveVersion is live now\033[0m" || >&2 echo -e "\033[0;31m## [Fail] website validation Fail: expected demo - actual $liveVersion\033[0m"
+              [[ $liveVersion == $(releaseSemVer) ]] && echo -e "\033[1;32m## [Passed] website validation Ok: $liveVersion is live now\033[0m" || >&2 echo -e "\033[0;31m## [Fail] website validation Fail: expected $(releaseSemVer) - actual $liveVersion\033[0m"
             displayName: 'validate website version'
             failOnStderr: true
